version: "3.7"
name: kide-bot-dev

services:
  node:
    container_name: kide-bot-dev-node
    image: ghcr.io/aleksilassila/kide-bot:latest
    build:
      target: development
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      NODE_ENV: development
    volumes:
      - ./prisma:/usr/src/app/prisma
    restart: unless-stopped
