FROM --platform=linux/amd64 node:18

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app
COPY *.lock /usr/src/app

RUN yarn install --frozen-lockfile

COPY . .

RUN npx prisma generate

CMD ["npm", "start" ]
