name: Build

on:
  push:
    branches:
      - master

jobs:
  push:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build containers
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml build

      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml push
